---
# Create and deploy a cluster with the Assisted Installer
#
# Example Usage:
#
# ansible-playbook -i ansible/inventory/cloud42.local ansible/bm-deploy.yml
#

- name: Creates a bare metal cluster with the assisted-installer
  hosts: bastion
  vars_files:
  - "vars/{{ cluster_name }}.yml"
  - vars/lab.yml
  roles:
  - validate-vars
  - bm-post-cluster-install
